export default{
    "data":{
        "memes":[
            {
                id:0,
                "name":"asdas",
                'url':"https://www.shutterstock.com/image-vector/shiba-inu-meme-dog-original-260nw-1969261210.jpg",
                'width':'1200',
                "height":"1200",
                "box_count":2
            },
            {
                id:1,
                "name":"asdas",
                'url':"https://marketplace.canva.com/EAEMDhEGHCE/1/0/1600w/canva-cat-before-coffee-after-coffee-two-photos-and-text-meme-QZiqeDqC-q4.jpg",
                'width':'1200',
                "height":"1200",
                "box_count":2
            },
            {
                id:2,
                "name":"asdas",
                'url':"https://media.istockphoto.com/id/1318934935/photo/infidelity-concept-unfaithful-womanizer-guy-turning-around-amazed-at-another-woman-while.jpg?b=1&s=612x612&w=0&k=20&c=_Oy6rfdJGPA86B_izM-BaSx9eHyHld9gEQnU7Nc1-j4=",
                'width':'1200',
                "height":"1200",
                "box_count":2
            },
            {
                id:3,
                "name":"asdas",
                'url':"https://media.istockphoto.com/id/538665020/photo/internet-meme-why-you-no-rage-face-3d-illustration.jpg?s=612x612&w=0&k=20&c=5D_g8Jy8kqg5Op2bb4RvcH8_6y0HGPqt29TKDrEqLyM=",
                'width':'1200',
                "height":"1200",
                "box_count":2
            }
        ]
    }
}